version: "3.3"

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080

  some-mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - 3306:3306